name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master  # или main, в зависимости от вашей основной ветки
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EASY_WA }}'
          channelId: live
          projectId: easy-wa  # замените на ID вашего проекта